### ISSUE TITLE
Feature request: add to biocontainers

### ISSUE THREAD

**Issue by cmatKhan** [BergmannLab/PascalX#12]
Hi all,

It would be nice if the dockerfile were added to [biocontainers](https://github.com/BioContainers/containers). Any interest?

**Comment by Dan-RAI** [comment]
Yes, we could look into this. Hopefully after the new v0.0.3 release is ready and stable.

**Comment by Dan-RAI** [comment]
Unfortunately, I do not have currently time to look into this. However, volunteers are welcome ...

**Comment by cmatKhan** [comment]
I realize I put 'biocontainers', but I meant bioconda (which would then automatically go to bioconda).

@wsjung and I are in the same lab -- we will see if we can find time. @Dan-RAI , would you like to review the bioconda recipe before we put in the pull request (assuming we get to it), or if it runs, are you happy for it to go?

**Comment by cmatKhan** [comment]
I'm having trouble getting this [bioconda recipe](https://github.com/cmatKhan/bioconda-recipes/tree/pascalx/recipes/pascalx) to work. I'm getting an error with regards to the c++ compiler. I believe this has to do with this requirement:

```
export LD_LIBRARY_PATH="/yourpath/PascalX/build/lib:$LD_LIBRARY_PATH"
```
But I'm not certain.

Here is the bioconda build error:

```
08:55:06 BIOCONDA INFO (OUT) +GXX=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-g++
08:55:06 BIOCONDA INFO (OUT) # Create build directories
08:55:06 BIOCONDA INFO (OUT) mkdir -p build
08:55:06 BIOCONDA INFO (OUT) mkdir -p build/include
08:55:06 BIOCONDA INFO (OUT) mkdir -p build/lib
08:55:06 BIOCONDA INFO (OUT) # Copy headers
08:55:06 BIOCONDA INFO (OUT) cp core/*.hpp build/include
08:55:06 BIOCONDA INFO (OUT) # Build core libraries
08:55:06 BIOCONDA INFO (OUT) g++ -fPIC -shared -rdynamic core/ruben.cpp -o build/lib/libruben.so -lquadmath -O2
08:55:06 BIOCONDA INFO (OUT) make: g++: No such file or directory
08:55:06 BIOCONDA INFO (OUT) make: *** [Makefile:16: all] Error 127
08:55:07 BIOCONDA INFO (OUT) Traceback (most recent call last):
08:55:07 BIOCONDA INFO (OUT)   File "/opt/conda/bin/conda-build", line 11, in <module>
08:55:07 BIOCONDA INFO (OUT)     sys.exit(execute())
08:55:07 BIOCONDA INFO (OUT)   File "/opt/conda/lib/python3.10/site-packages/conda_build/cli/main_build.py", line 590, in execute
08:55:07 BIOCONDA INFO (OUT)     api.build(
08:55:07 BIOCONDA INFO (OUT)   File "/opt/conda/lib/python3.10/site-packages/conda_build/api.py", line 250, in build
08:55:07 BIOCONDA INFO (OUT)     return build_tree(
08:55:07 BIOCONDA INFO (OUT)   File "/opt/conda/lib/python3.10/site-packages/conda_build/build.py", line 3638, in build_tree
08:55:07 BIOCONDA INFO (OUT)     packages_from_this = build(
08:55:07 BIOCONDA INFO (OUT)   File "/opt/conda/lib/python3.10/site-packages/conda_build/build.py", line 2506, in build
08:55:07 BIOCONDA INFO (OUT)     utils.check_call_env(
08:55:07 BIOCONDA INFO (OUT)   File "/opt/conda/lib/python3.10/site-packages/conda_build/utils.py", line 405, in check_call_env
08:55:07 BIOCONDA INFO (OUT)     return _func_defaulting_env_to_os_environ("call", *popenargs, **kwargs)
08:55:07 BIOCONDA INFO (OUT)   File "/opt/conda/lib/python3.10/site-packages/conda_build/utils.py", line 381, in _func_defaulting_env_to_os_environ
08:55:07 BIOCONDA INFO (OUT)     raise subprocess.CalledProcessError(proc.returncode, _args)
08:55:07 BIOCONDA INFO (OUT) subprocess.CalledProcessError: Command '['/bin/bash', '-o', 'errexit', '/opt/conda/conda-bld/pascalx_1717595607201/work/conda_build.sh']' returned non-zero exit status 2.
08:55:13 BIOCONDA ERROR COMMAND FAILED (exited with 1): docker run -t --net host --rm -v /tmp/tmpvhlzq_vc/build_script.bash:/opt/build_script.bash -v /home/chase/miniforge3/envs/bioconda/conda-bld:/opt/host-conda-bld -v /home/chase/code/bioconda-recipes/recipes/pascalx:/opt/recipe -e LANG=en_US.UTF-8 -e HOST_USER_ID=1001 quay.io/bioconda/bioconda-utils-build-env-cos7:3.3.0 /bin/bash /opt/build_script.bash

08:55:13 BIOCONDA ERROR BUILD FAILED recipes/pascalx
08:55:13 BIOCONDA INFO (COMMAND) conda build purge
08:55:13 BIOCONDA ERROR BUILD SUMMARY: of 1 recipes, 1 failed and 0 were skipped. Details of recipes and environments follow.
08:55:13 BIOCONDA ERROR BUILD SUMMARY: FAILED recipe recipes/pascalx
```

These are the instructions for testing bioconda recipes locally:

https://bioconda.github.io/contributor/building-locally.html#using-bioconda-utils

If you do happen to have a chance to look at the recipe, and maybe try to build it, and have any ideas on how to adjust the build.sh, or possibly adjust the makefile itself, I would be interested.

**Comment by Dan-RAI** [comment]
This line seems to be the problem:
```
g++ -fPIC -shared -rdynamic core/ruben.cpp -o build/lib/libruben.so -lquadmath -O2
08:55:06 BIOCONDA INFO (OUT) make: g++: No such file or directory
```

You might have to use absolute paths for the `cpp` and `so`. Or there is a problem with `quadmath`. On which system are you building ? Linux?
