### ISSUE TITLE
Series evaluation exceeded 1000000 iterations, giving up now

### ISSUE THREAD

**Issue by PatrickDeelen** [BergmannLab/PascalX#22]
I'm trying to run pascalX (https://www.nature.com/articles/s41586-022-05275-y) on the latest height gwas and get the following error: 

`terminate called after throwing an instance of 'boost::wrapexcept<boost::math::evaluation_error>'
what():  Error in function boost::math::tgamma<N5boost14multiprecision6numberINS0_8backends13cpp_bin_floatILj500ELNS2_15digit_base_typeE10EviLi0ELi0EEELNS0_26expression_template_optionE0EEE>(N5boost14multiprecision6numberINS0_8backends13cpp_bin_floatILj500ELNS2_15digit_base_typeE10EviLi0ELi0EEELNS0_26expression_template_optionE0EEE,N5boost14multiprecision6numberINS0_8backends13cpp_bin_floatILj500ELNS2_15digit_base_typeE10EviLi0ELi0EEELNS0_26expression_template_optionE0EEE): Series evaluation exceeded 1000000 iterations, giving up now.      `

Can you recommend how to proceed if this happens?

**Comment by PatrickDeelen** [comment]
A more information appears after I killed the run but it is hard to read because of the  progress bars that overlapped with the stack trace:
```

0%|                                                                                                                                                                                                                                                                                                                          [ estimated time left: ? ]  0%|                                                                                                                                                                                                                                                                                                                    [ estimated time left: 7:17:13 ]  0%|▏                                                                                                                                                                                                                                                                                                                   [ estimated time left: 2:53:36 ]  0%|▎                                                                                                                                                                                                                                                                                                                   [ estimated time left: 2:31:58 ]  0%|▋                                                                                                                                                                                                                                                                                                                   [ estimated time left: 1:01:15 ]  6%|██████████████████▋                                                                                                                                                                                                                                                                                                   [ estimated time left: 18:30 ]terminate called after throwing an instance of 'boost::wrapexcept<boost::math::evaluation_error>'                                                                                                                                                                                                                          [ estimated time left: 11:35 ]
  what():  Error in function boost::math::tgamma<N5boost14multiprecision6numberINS0_8backends13cpp_bin_floatILj500ELNS2_15digit_base_typeE10EviLi0ELi0EEELNS0_26expression_template_optionE0EEE>(N5boost14multiprecision6numberINS0_8backends13cpp_bin_floatILj500ELNS2_15digit_base_typeE10EviLi0ELi0EEELNS0_26expression_template_optionE0EEE,N5boost14multiprecision6numberINS0_8backends13cpp_bin_floatILj500ELNS2_15digit_base_typeE10EviLi0ELi0EEELNS0_26expression_template_optionE0EEE): Series evaluation exceeded 1000000 iterations, giving up now.                                                                                                                    [ estimated time left: 3:21:04 ]
 15%|█████████████████████████████████████████████▋                                                                                                                                                                                                                                                                      [ estimated time left: 2:28:38 ]^CTraceback (most recent call last):████████████████████████████████████████████████████████▊                                                                                                                                                                                                                              [ estimated time left: 54:12 ]
  File "/groups/umcg-fg/tmp01/projects/downstreamer/PascalX_bundle/runRealGWAS/runRealGWAS.py", line 38, in <module>                                                                                                                                                                                                       [ estimated time left: 42:01 ]
    R = Scorer.score_all(parallel=int(args.threads), method="auto",autorescore=True)                                                                                                                                                                                                                                       [ estimated time left: 10:50 ]
  File "/PascalX/python/PascalX/genescorer.py", line 912, in score_all                                                                                                                                                                                                                                                     [ estimated time left: 20:45 ]
    return self.score_chr([i for i in range(1,23)],True,method,mode,reqacc,intlimit,parallel,nobar,autorescore)                                                                                                                                                                                                            [ estimated time left: 05:40 ]
  File "/PascalX/python/PascalX/genescorer.py", line 890, in score_chr                                                                                                                                                                                                                                                   [ estimated time left: 1:21:24 ]
    return self.score(G,parallel,unloadRef,method,mode,reqacc,intlimit,nobar,autorescore)                                                                                                                                                                                                                                  [ estimated time left: 08:47 ]
  File "/PascalX/python/PascalX/genescorer.py", line 747, in score                                                                                                                                                                                                                                                       [ estimated time left: 8:28:00 ]
    results = [result.get() for result in result_objs]    ███████████████▋                                                                                                                                                                                                                                               [ estimated time left: 8:18:27 ]
  File "/PascalX/python/PascalX/genescorer.py", line 747, in <listcomp>                                                                                                                                                                                                                                                  [ estimated time left: 5:25:04 ]
    results = [result.get() for result in result_objs]    ██████████████████████████████████████████████▍                                                                                                                                                                                                                  [ estimated time left: 30:53 ]
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 768, in get█████████████████████████████▏                                                                                                                                                                                                                       [ estimated time left: 17:54 ]
    self.wait(timeout)█████████████▋                                                                                                                                                                                                                                                                                       [ estimated time left: 12:26 ]
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 765, in wait                                                                                                                                                                                                                                                  [ estimated time left: 5:44:24 ]
    self._event.wait(timeout)                                                                                                                                                                                                                                                                                              [ estimated time left: 44:53 ]
  File "/usr/lib/python3.10/threading.py", line 607, in wait                                                                                                                                                                                                                                                               [ estimated time left: 07:23 ]
    signaled = self._cond.wait(timeout)████████████████████████████████████████████████▊                                                                                                                                                                                                                                   [ estimated time left: 04:12 ]
  File "/usr/lib/python3.10/threading.py", line 320, in wait████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                                                                                              [ estimated time left: 07:54 ]
    waiter.acquire()
KeyboardInterrupt
```

**Comment by Dan-RAI** [comment]
Which scoring algorithm are you using ? The default one ? 

As a temporary fix, I would recommend to exclude the gene from the scoring and try to score the gene with one of the other algorithms.

**Comment by Dan-RAI** [comment]
Note that the progress bar can be disabled by setting nobar=True

**Comment by Dan-RAI** [comment]
With the current master branch and default settings, I have NOT been able to reproduce the error for the summary stats "GIANT_HEIGHT_YENGO_2022_GWAS_SUMMARY_STATS_EUR" .

Please let me know the precise settings used so that I can investigate further.

**Comment by PatrickDeelen** [comment]
> Which scoring algorithm are you using ? The default one ?

We used this API command: `Scorer.score_all(parallel=int(args.threads), method="auto",autorescore=True)`

> As a temporary fix, I would recommend to exclude the gene from the scoring and try to score the gene with one of the other algorithms.

I suppose the best way to find the failed gene is to use `Score.score(gene, ...` to see where it fails. 

> Note that the progress bar can be disabled by setting nobar=True

I will try using the `nobar = True` to get a proper stack trace.

**Comment by PatrickDeelen** [comment]
Below is the full error message. Without the progress bars it became clear that the stacks trace is only the result of the keyboard interrupt. That was need because the program does not seem to recover from this error and won't finish even if the progress bars indicate 100%.  

`Starting scoring...
terminate called after throwing an instance of 'boost::wrapexcept<boost::math::evaluation_error>'
  what():  Error in function boost::math::tgamma<N5boost14multiprecision6numberINS0_8backends13cpp_bin_floatILj500ELNS2_15digit_base_typeE10EviLi0ELi0EEELNS0_26expression_template_optionE0EEE>(N5boost14multiprecision6numberINS0_8backends13cpp_bin_floatILj500ELNS2_15digit_base_typeE10EviLi0ELi0EEELNS0_26expression_template_optionE0EEE,N5boost14multiprecision6numberINS0_8backends13cpp_bin_floatILj500ELNS2_15digit_base_typeE10EviLi0ELi0EEELNS0_26expression_template_optionE0EEE): Series evaluation exceeded 1000000 iterations, giving up now.
`

**Comment by Dan-RAI** [comment]
ok, I think the origin of the problem is that this GWAS has some SNPs with p-value around 5e-324, which is the smallest one can squeeze into a float (denormalized). However, such small p-values may be later a problem in the C code as the (normalized) double type supports only up to 1.8e-308.  

Therefore, one simple possibility would be to cut the input p-values in the GWAS, say around 1e-300. This may already solve your problem. 

Which version / commit are you using ? I suspect that the error actually pops up in the rescoring. It seems that your version uses as default for the rescoring the satterthwaite approximation, as the calculation of the gamma function fails (you can verify by looking in the genescorer.py and search for autorescore == True). The more recent version uses the pearson approximation by default for the rescoring, which does not seem to fail for this GWAS.

**Comment by PatrickDeelen** [comment]
I see now that we indeed are using a bit older version of the code, thank you for pointing this out. We have been using this fork: https://github.com/curzuat/PascalX and I see now that it is 25 commits behind your original. 

But it does seem to use the Pearson method. Line 769 of our version: https://github.com/curzuat/PascalX/blob/main/python/PascalX/genescorer.py

The reason we made a fork is because we wanted to know what the minimum SNP p-value for a gene was and how many SNPs where used for each gene. Are you open to use creating a pull request for these changes so that we can use the main branch in the future? 

Again, thank you for your help!

**Comment by Dan-RAI** [comment]
I see, than somewhere else the Gamma function computation in the C part is failing. Will give it a try today with a hard threshold of 1e-300 upon GWAS p-value import. Hopefully the Height GWAS works with that thresholding on the current master branch. 

Regarding your new functionality:

Yes, of course, feel free to open a pull request for new functionality which you think may be of wider interest. Best to use one request per new feature. For instance, your two mentioned functionalities probably would fit well as an extension of the existing "def get_geneinfo(self,gene):" function in genescorer.py .

**Comment by Dan-RAI** [comment]
I merged into the master a modified load_GWAS which allows for p-value cutoff (as default set to 1e-300). 

The Height GWAS successfully completed on the current master under "auto". However, it is rather slow with the "auto" method as the GWAS is very over-powered (needed several hours to complete). I would recommend to use the "saddle" method for such highly powered GWAS, as it will only take a few minutes to complete, and it will be able to resolve the signals above 1e-100 up to ~1e-300 (of which there are plenty in this GWAS).

**Comment by PatrickDeelen** [comment]
Great, thank you.  We are going to try it. 

Can you provide some more general advice on the select the method? Is the auto method more powerful in the case of low powered GWAS? When is it roughly better to start using saddle compared to auto?

**Comment by Dan-RAI** [comment]
That depends on how important it is for your application to be sure that the ordering / ranking is correct. If it is important that the ranking gets resolved as well as possible, I would first run a saddle scoring (takes a few minutes), and then score again the subset bulk of genes with scores larger than, say 1e-80, with the auto method. ( Filtering out in this way first the genes with extremely small scores should significantly speedup the auto scoring. )

**Comment by PatrickDeelen** [comment]
Okay, let me just rephrase this so that I can be 100% sure I understand. 

* Saddle
  * Fast
  * Mostly accurate but might have small deviations in ordering of genes because p-value is only a close approximate. 
* Auto
  * Slow
  * Accurate
  * Not suited for p-values <1e-80
  
Did I understand it correctly?

**Comment by Dan-RAI** [comment]
Regarding the summary.

Almost:

The auto (exact) method is guaranteed to work up to roughly 1e-100. I mentioned an arbitrary threshold of 1e-80 for performance reasons: The auto method is in general quite fast as well, just not always: For a few genes with very small p-values it can take ages.

Regarding the gamma function:

I do not see this error. It might be an issue with the boost library version installed on your system. Which version do you have ?

Until we find out the reason for the gamma function problem, you can try to manually rescore the missing genes with another algorithm. There is the .rescore function in the genescorer into which you can feed the output (lets call it R) of the original scoring run. It will rescore R[1] with the specified method and put the results into R[0] if successful. Ruben will always work if limits are set high enough. 

The reason why the saddle method fails is because the saddle approximation does not work mathematically in one particular situation, and I set the threshold to detect this situation rather conservative, in order to be on the safe side (though I might have set it too conservative). This does not necessarily mean that these p-values are extremely small. So there is a chance that auto might work fine and fast on these genes.

**Comment by Dan-RAI** [comment]
Closed because of inactivity. If issue still persists, please open new one.
